### PR TITLE
Create kr.txt

### PR DESCRIPTION
**Pull request by Twotoolus-FLY-LShst**
Korean language here! thank you make this mod.

### CODE REVIEW

**Comment by pcfantasy** [comment]
thank you

**Comment by pcfantasy** [comment]
@ToothlessFLY-LShst 

What is your steam ID, I want to thank you in steampage.

**Comment by Twotoolus-FLY-LShst** [comment]
@pcfantasy

https://steamcommunity.com/id/lshst/ here!
OA< b

**Comment by pcfantasy** [comment]
@ToothlessFLY-LShst 

Ok, thanks.

**Pull request merged**
